<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous" defer></script>
        <!-- CSS -->
        <link rel="stylesheet" href="views/site/css/style.css">
        <!-- JavaScript -->
        <script src="views/site/js/script.js" defer></script>
        <title>Login</title>
    </head>
    <body>
        
        <div class="container col-11 col-md-9" id="form-container">
            <div class="row align-items-center gx-5">
                <div class="col-md-6 order-md-2">
                    <h2>Please login to continue</h2>
                    <form class="needs-validation" novalidate>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Type your e-mail" required>
                            <label for="email" class="form-label">E-mail:</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="password" name="password" placeholder="Type your password" required>
                            <label for="password" class="form-label">Password:</label>
                        </div>
                        <input type="submit" value="Login" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-md-6 order-md-1">
                    <div class="d-none d-md-block col-md-12">
                        <img class="img-fluid" src="views/site/img/sign_in.svg" alt="log into the system">
                    </div>
                    <div class="col-12" id="link-container">
                        <a href="register">I don't have a record yet</a>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>