<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous" defer></script>
        <!-- CSS -->
        <link rel="stylesheet" href="views/site/css/style.css">
        <!-- JavaScript -->
        <script src="views/site/js/script.js" defer></script>
        <title>Login</title>
    </head>
    <body>
        
        <div class="container col-11 col-md-9" id="form-container">
            <div class="row align-items-center gx-5">
                <div class="col-md-6">
                    <h2>Make your registration</h2>
                    <form class="needs-validation" novalidate>
                        <div class="form-floating mb-3" >
                            <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Type your first name" required>
                            <label for="firstname" class="form-label">Type your first name:</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Type your last name" required>
                            <label for="lastname" class="form-label">Type your last name:</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="email" name="email" placeholder="Type your e-mail" required>
                            <label for="email" class="form-label">Type your e-mail:</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="password" name="password" placeholder="Type your password" required>
                            <label for="password" class="form-label">Type your password:</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="confirmpassword" class="form-control" id="confirmpassword" name="confirmpassword" placeholder="Confirm your password" required>
                            <label for="confirmpassword" class="form-label">Confirm your password:</label>
                        </div>
                        <div class="mb-3">
                            <div class="form-check mb-2">
                                <input type="checkbox" name="agree-form" id="agree-form" class="form-check-input" required>
                                <label for="agree-form">I accept the <a href="#">terms of service</a></label>
                            </div>
                        </div>
                        <div class="mb-3">
                            <div class="form-check mb-2">
                                <input type="checkbox" name="newsletter" id="newsletter" class="form-check-input">
                                <label for="newsletter">I want to receive the newsletter</label>
                            </div>
                        </div>
                        <input type="submit" value="Create account" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-md-6">
                    <div class="row align-items-center">
                        <div class="d-none d-md-block col-12">
                            <img src="views/site/img/hello.svg" alt="Registration screen" class="img-fluid">
                        </div>
                        <div class="col-12" id="link-container">
                        <a href="login">I already have a record</a>
                    </div>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>